<?php

namespace LazyBlog\LazyModelBundle\Repository;

/**
 * CategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */

use Doctrine\ORM\EntityRepository;

class CategoryRepository extends EntityRepository
{
    /**
     * @var string $result
     *
     * @return Category
     */
    public function findId($id)
    {
        $qb = $this->getQueryBuilder()
            ->orderBy('c.id')
            ->setMaxResults($id);

        return $qb->getQuery()->getSingleResult();
    }

    /**
     * @return \Doctrine\ORM\QueryBuilder
     */
    private function getQueryBuilder()
    {
        $em = $this->getEntityManager();

        $qb = $em->getRepository('LazyModelBundle:Category')
            ->createQueryBuilder('c');

        return $qb;
    }
}
