<?php

namespace LazyBlog\LazyModelBundle\Repository;

use Doctrine\ORM\EntityRepository;
use LazyBlog\LazyModelBundle\Entity\Comment;

/**
 * CommentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentRepository extends EntityRepository
{
    /**
     * Найти первый пост
     *
     * @return Comment
     */
    public function firstFirst()
    {
        $qb = $this->getQueryBuilder()
            ->orderBy('t.id', 'asc')
            ->setMaxResults(10);

        return $qb->getQuery()->getResult();
    }

    private function getQueryBuilder()
    {
        $em = $this->getEntityManager();

        $qb = $em->getRepository('LazyModelBundle:Post')->createQueryBuilder('p');

        return $qb;
    }
}
